# ----
# Site

title: Iomote
description: Iomote documentation.
url: https://iomote.com
google_analytics_key:
permalink: pretty

collections:
  platform:
    title: MyMote platform
    position: 1
  gettingstarted:
    title: Getting Started
    position: 2
  gateway:
    title: X400 Gateway
    position: 3
  arduino:
    title: Iomote Library
    position: 4
  restapi:
    title: Rest API
    position: 5
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  - Notepad.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

