# ----
# Site

title: Aviator
description: Jekyll template for API documentation.
url: https://example.com
google_analytics_key:
permalink: pretty

collections:
  platform:
    title: MyMote platform
    position: 1
  gateway:
    title: X400 Gateway
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE
  - Notepad.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

